#! /bin/sh

sxhkd &

bspc monitor eDP1 -d I II III IV V VI VII VIII IX X

bspc config border_width        	1
bspc config window_gap         		3 
bspc config border_radius		10
bspc config split_ratio          	0.58
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config focus_follows_pointer       false
bspc config history_aware_focus         true
bspc config borderless_monocle   	true
bspc config gapless_monocle      	true

### Colors
bspc config focused_border_color "#0d00ff"

bspc rule -a Zathura state=tiled

$HOME/.config/polybar/launch.sh
compton &
nm-applet &
kdeconnect-indicator &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
blueman-applet &
dunst &
feh --bg-fill $HOME/Pictures/Wallpapers/wallpaper1.jpg &
gebaard -b
